apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daytrader-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: daytrader-session
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
